### ISSUE TITLE
JPG file mis-identified by file program during batch loading - "invalid page image file"

### ISSUE THREAD

**Issue by lydiam** [FLVC/offline-ingest#22]
I’ve gotten a few book loader errors of the following sort:

The Book Package FA00000261 has an invalid page image file: Page file 29.jpg is of unsupported type application/octet-stream, but it must be one of image/jp2, image/jpeg, or image/tiff.  (The file is in /ssa/d2i/FAU_FHP_cant-load/FA00000261).  I sent it through the description service (description.fcla.edu) and it came back as a well-formed and valid JPEG.

**Comment by grf** [comment]
We use the 'file' program to identify images.   Occasionally it mischaracterizes a image:

   $ file *.jpg
   28.jpg:      JPEG image data, JFIF standard 1.01
   29.jpg:     Minix filesystem, V3, 61267 zones

Other image processing utilities seem to get the JPEG correct,  however,  including display tools.

One can quickly check a directory full of images for the 'file' problem as so:

   $ file *.jpg | grep -v JPEG

The fix is straight-forward: use our tools to convert the file to another image format, then back to a jpeg:

   $ jpegtopnm bad.jpg | pnmtojpeg > good.jpg

Replace the bad file with the good one, after displaying them both to make sure no obvious artifacts were produced.
